from __future__ import annotations


INTENT_LOW_CONFIDENCE_THRESHOLD = 0.60
INTENT_LLM_ESCALATION_THRESHOLD = 0.80
INTENT_MARGIN_MIXED_THRESHOLD = 0.12
INTENT_HIGH_AMBIGUITY_THRESHOLD = 0.45
SHORT_FOLLOWUP_MAX_LEN = 42
